# Site settings
title: Trepverterless blog website
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Trepverterless
user_description: this is my first test blog
user_title: wellcome to my blog
email: 1367149807@qq.com
twitter_username: einstein
github_username:  trepverterless
gplus_username:  einstein

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
